apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: kustomization-deployments
  namespace: argocd
spec:
  project: defaultÂ  

  source:
    repoURL: https://github.com/knallapaneni007/argocd-apps-of-apps.git
    path: kustomization/infrastructure/minikube/*
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc